apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: togglemaster
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h flag-targeting-db -U shared_user; do echo "aguardando flag-targeting-db..."; sleep 2; done
      containers:
        - name: flag-service
          image: togglemaster-flag-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "250m"
              memory: "192Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: flag-config
                  key: PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: flag-secret
                  key: DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: flag-config
                  key: AUTH_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: togglemaster
spec:
  selector:
    app: flag-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
