apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

images:
- name: 376903139600.dkr.ecr.us-east-1.amazonaws.com/auth-service
  newName: 376903139600.dkr.ecr.us-east-1.amazonaws.com/auth-service
  newTag: cc57cbfd86a0d34349908312ac56a1a7235028da
