apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- db-init.yaml

images:
- name: 376903139600.dkr.ecr.us-east-1.amazonaws.com/flag-service
  newName: 376903139600.dkr.ecr.us-east-1.amazonaws.com/flag-service
  newTag: ff0ca470acdea0d10432251e71a2239e44a09ef8
