apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: togglemaster
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - auth_user
                - -d
                - auth_db
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: auth-db-init

---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: togglemaster
spec:
  selector:
    app: auth-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
