apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: togglemaster
  region: us-east-1
  version: "1.32"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: evaluation-sa
        namespace: togglemaster
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: ["sqs:SendMessage", "sqs:GetQueueUrl"]
            Resource: "arn:aws:sqs:us-east-1:376903139600:togglemaster-analytics-events"
    - metadata:
        name: analytics-sa
        namespace: togglemaster
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl",
              ]
            Resource: "arn:aws:sqs:us-east-1:376903139600:togglemaster-analytics-events"
          - Effect: Allow
            Action: ["dynamodb:PutItem"]
            Resource: "arn:aws:dynamodb:us-east-1:376903139600:table/ToggleMasterAnalytics"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: ng-togglemaster
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 20
