apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/part-of: togglemaster-observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: otel-collector
  endpoints:
    - port: prom-exporter
      path: /metrics
      interval: 30s
