apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      serviceAccountName: evaluation-sa
      containers:
        - name: evaluation-service
          image: 376903139600.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:latest
          ports:
            - containerPort: 8004
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: PORT
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: REDIS_URL
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: TARGETING_SERVICE_URL
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: AWS_SQS_URL
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: evaluation-config
                  key: AWS_REGION
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-secret
                  key: SERVICE_API_KEY
