apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/376903139600/togglemaster-analytics-events"
