name: flag-service CI

on:
  push:
    branches: [main]
    paths:
      - "services/flag-service/**"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/reusable-python-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/flag-service/**"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/reusable-python-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-python-ci.yml
    permissions:
      id-token: write
      contents: write
    with:
      service: flag-service
